import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import curatedRecipes from './recipes.json';
import KitchenStory from './KitchenStory';
type Recipe={id:number;title:string;category:string;minutes:number|null;yield:string;description:string;ingredients:string[];steps:string[];source:string;publisher:string;image:string;search?:string;detailChunk?:number;fullRecipe?:boolean};
const hero='https://images.unsplash.com/photo-1535920527002-b35e96722eb9?auto=format&fit=crop&w=2000&q=85';
const Arrow=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" strokeWidth="1.6"/></svg>;
const Bookmark=({filled=false}:{filled?:boolean})=><svg width="20" height="20" viewBox="0 0 24 24" fill={filled?'currentColor':'none'} aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4V3Z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/></svg>;
function FoodImage({src,alt,className=''}:{src:string;alt:string;className?:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return failed?<div className={`image-fallback ${className}`}>{alt}<span>Photo unavailable</span></div>:<img className={className} src={src} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>;}
export default function App(){
 const [recipes,setRecipes]=useState<Recipe[]>(curatedRecipes),[catalogStatus,setCatalogStatus]=useState('loading'),[catalogRetry,setCatalogRetry]=useState(0),[visibleCount,setVisibleCount]=useState(24),[detailError,setDetailError]=useState(false),[detailRetry,setDetailRetry]=useState(0);
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[savedOnly,setSavedOnly]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Recipe|null>(null),[saved,setSaved]=useState<number[]>(()=>{try{const v=JSON.parse(localStorage.getItem('cooksmart-saved')||'[]');return Array.isArray(v)?v.filter((x:unknown)=>typeof x==='number'):[]}catch{return[]}}),[storageError,setStorageError]=useState(false);
 const [splash,setSplash]=useState(()=>{try{return !sessionStorage.getItem('cooksmart-visited')}catch{return false}}),[count,setCount]=useState(0);const dialog=useRef<HTMLDialogElement>(null);const heroRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!splash)return;const started=performance.now();const timer=setInterval(()=>{const v=Math.min(100,Math.floor((performance.now()-started)/20));setCount(v);if(v===100){clearInterval(timer);setTimeout(()=>{setSplash(false);try{sessionStorage.setItem('cooksmart-visited','1')}catch{}},900)}},20);return()=>clearInterval(timer)},[splash]);
 useEffect(()=>{try{localStorage.setItem('cooksmart-saved',JSON.stringify(saved));setStorageError(false)}catch{setStorageError(true)}},[saved]);
 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[selected]);
 useEffect(()=>{const el=heroRef.current;if(!el)return;const image=new Image();const update=()=>{const bounds=el.getBoundingClientRect();const scale=Math.max(bounds.width/(image.naturalWidth||bounds.width),bounds.height/(image.naturalHeight||bounds.height));const width=(image.naturalWidth||bounds.width)*scale;const height=(image.naturalHeight||bounds.height)*scale;el.querySelectorAll<HTMLElement>('.masked').forEach(c=>{const b=c.getBoundingClientRect();c.style.backgroundSize=`${width}px ${height}px`;c.style.backgroundPosition=`-${b.left-bounds.left+(width-bounds.width)/2}px -${b.top-bounds.top+(height-bounds.height)/2}px`})};image.onload=update;image.src=hero;const observer=new ResizeObserver(update);observer.observe(el);update();return()=>{observer.disconnect();image.onload=null}},[]);
 useEffect(()=>{const controller=new AbortController();setCatalogStatus('loading');fetch('/dataset/index.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json()}).then((data:Recipe[])=>{setRecipes([...curatedRecipes,...data.map(r=>({...r,ingredients:[],steps:[]}))]);setCatalogStatus('ready')}).catch(e=>{if(e.name!=='AbortError')setCatalogStatus('error')});return()=>controller.abort()},[catalogRetry]);
 useEffect(()=>{setDetailError(false);if(!selected?.fullRecipe||selected.steps.length)return;const controller=new AbortController();const id=selected.id;fetch(`/dataset/details/${selected.detailChunk}.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Recipe unavailable');return r.json()}).then(data=>{if(!data[id])throw Error('Recipe missing');setSelected(prev=>prev?.id===id?data[id]:prev)}).catch(e=>{if(e.name!=='AbortError')setDetailError(true)});return()=>controller.abort()},[selected?.id,detailRetry]);
 const deferredQuery=useDeferredValue(query.trim().toLowerCase());
 const filtered=useMemo(()=>{const savedIds=new Set(saved);const words=deferredQuery.split(/\s+/).filter(Boolean);return recipes.filter(r=>(category==='All'||r.category===category||(category==='30 min or less'&&r.minutes!==null&&r.minutes<=30))&&(!savedOnly||savedIds.has(r.id))&&words.every(word=>(r.search||`${r.title} ${r.ingredients.join(' ')}`.toLowerCase()).includes(word)))},[recipes,category,savedOnly,saved,deferredQuery]);
 useEffect(()=>setVisibleCount(24),[query,category,savedOnly]);
 const toggle=(id:number)=>setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const browse=(only=false)=>{setSavedOnly(only);setCategory('All');setQuery('');setMenu(false);document.getElementById('recipes')?.scrollIntoView({behavior:'smooth'})};
 return <>
 {splash&&<div className={`splash ${count===100?'leaving':''}`} aria-hidden="true"><span>{count.toString().padStart(2,'0')}</span><small>COOKSMART / THE EVERYDAY KITCHEN</small></div>}
 <a className="skip" href="#recipes">Skip to recipes</a>
 <header><a href="#home" className="logo" aria-label="CookSmart home">COOK<br/>SMART<span>good food. made by you.</span></a><nav aria-label="Main navigation"><button onClick={()=>browse()}>The recipes</button><a href="#weekend">Weekend baking</a><button className="saved-nav" onClick={()=>browse(true)}><Bookmark/> My collection <span>{saved.length.toString().padStart(2,'0')}</span></button></nav><button className="mobile-toggle" aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></header>
 {menu&&<nav className="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><button onClick={()=>browse()}>The recipes</button><a href="#weekend" onClick={()=>setMenu(false)}>Weekend baking</a><button onClick={()=>browse(true)}>My collection ({saved.length})</button></nav>}
 <main><KitchenStory onExplore={() => browse()} />
 <section className="recipe-section" id="recipes"><div className="section-heading"><div><p className="eyebrow">01 / THE RECIPE COLLECTION</p><h2>{savedOnly?'Your good-food list.':'What sounds good?'}</h2></div><p>{savedOnly?'Your favorites, saved in this browser.':'Weeknight staples. Sunday classics.\nSomething worth making from scratch.'}</p></div>
 <div className="controls"><div className="categories" aria-label="Recipe categories">{['All','Dinner','Breakfast','Baking','Salads','Drinks','Other','30 min or less'].map(c=><button className={category===c?'active':''} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="6" stroke="currentColor" strokeWidth="1.5"/><path d="m15 15 6 6" stroke="currentColor" strokeWidth="1.5"/></svg><input aria-label="Search recipes or ingredients" value={query} onChange={e=>setQuery(e.target.value)} placeholder="A dish, an ingredient…"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label></div>
 <div className="results-line"><span aria-live="polite">{filtered.length.toLocaleString()} recipes {savedOnly?'in your collection':'to make your own'}</span>{savedOnly&&<button onClick={()=>setSavedOnly(false)}>View all recipes</button>}<span>CURATED FROM REAL RECIPE KITCHENS</span></div>
 {storageError&&<p role="status">Browser storage is unavailable. Your favorites will last until you leave this page.</p>}
 <div className="recipe-grid">{filtered.slice(0,visibleCount).map((r,i)=><article className="recipe-card" key={r.id}><div className="photo-wrap"><button className="photo-button" onClick={()=>setSelected(r)} aria-label={`View ${r.title}`}><FoodImage src={r.image} alt={r.title}/></button><span className="tag">{r.category}</span><button className={`save ${saved.includes(r.id)?'is-saved':''}`} onClick={()=>toggle(r.id)} aria-label={`${saved.includes(r.id)?'Unsave':'Save'} ${r.title}`} aria-pressed={saved.includes(r.id)}><Bookmark filled={saved.includes(r.id)}/></button></div><div className="card-meta"><span>{r.minutes!==null?r.minutes+' MIN · ':''}{r.yield?r.yield.toUpperCase():'FULL RECIPE'}</span><span>{String(i+1).padStart(2,'0')}</span></div><button className="recipe-title" onClick={()=>setSelected(r)}><h3>{r.title}</h3><Arrow/></button><p>{r.description}</p><span className="source-credit">{r.source?<a href={r.source} target="_blank" rel="noreferrer">Recipe & photo: {r.publisher}</a>:"Ingredients & instructions included"}</span></article>)}</div>
 {catalogStatus==='loading'&&<p role="status">Loading the recipe collection…</p>}
 {catalogStatus==='error'&&<p role="alert">The recipe archive could not load. <button className="outline-button" onClick={()=>setCatalogRetry(n=>n+1)}>Try again</button></p>}
 {filtered.length>visibleCount&&<div className="load-more"><p>Showing {Math.min(visibleCount,filtered.length).toLocaleString()} of {filtered.length.toLocaleString()} recipes</p><button className="black-button" onClick={()=>setVisibleCount(n=>n+24)}>Show 24 more recipes</button></div>}
 {!filtered.length&&catalogStatus!=='loading'&&<div className="empty"><h3>{savedOnly?'Room for a new favorite.':'Nothing on the menu just yet.'}</h3><p>{savedOnly?'Tap the bookmark on a recipe to keep it here.':'Try a different dish, ingredient, or category.'}</p><button className="black-button" onClick={()=>browse()}>Browse all recipes <Arrow/></button></div>}
 </section>
 <section className="weekend" id="weekend"><div className="weekend-copy"><p className="eyebrow">02 / TAKE IT SLOW</p><h2>Leave room<br/>for the<br/>weekend.</h2><p>Butter on the counter. Something good in the oven. A little time to make it yours.</p><button className="black-button" onClick={()=>{browse();setCategory('Baking')}}>Explore the baking recipes <Arrow/></button></div><div className="weekend-image"><FoodImage src={hero} alt="A freshly baked lattice apple pie"/><div className="glass-card"><div><span>THE WEEKEND PICK</span><h3>All-American<br/>apple pie</h3></div><button className="round-button" aria-label="View apple pie" onClick={()=>setSelected(recipes[6])}><Arrow/></button></div></div></section>
 </main><footer><a className="footer-brand" href="#home">COOKSMART</a><div><p>Good food starts with a little curiosity.</p><p className="fine">Explore complete recipes from the collection, plus our original curated recipe previews.<br/>Saved recipes stay on this device.</p></div><a href="#home">Back to top ↑</a></footer>
 <dialog ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}} aria-labelledby="recipe-heading">{selected&&<><button className="close-dialog" onClick={()=>setSelected(null)} aria-label="Close recipe">×</button><FoodImage className="dialog-image" src={selected.image} alt={selected.title}/><div className="dialog-content"><p className="eyebrow">{selected.category}{selected.minutes!==null?` / ${selected.minutes} MIN`:''}{selected.yield?` / ${selected.yield}`:''}</p><h2 id="recipe-heading">{selected.title}</h2><p>{selected.description}</p><div className="detail-actions">{selected.source&&<a className="black-button" href={selected.source} target="_blank" rel="noreferrer">Full recipe & measurements <Arrow/></a>}<button className="outline-button" onClick={()=>toggle(selected.id)}><Bookmark filled={saved.includes(selected.id)}/>{saved.includes(selected.id)?'Saved':'Save recipe'}</button></div>{selected.fullRecipe&&!selected.steps.length&&(detailError?<p role="alert">This recipe could not load. <button className="outline-button" onClick={()=>setDetailRetry(n=>n+1)}>Try again</button></p>:<p role="status">Loading ingredients and instructions…</p>)}<h3>{selected.fullRecipe?'Ingredients & quantities':'Key ingredients'}</h3><div className="ingredients">{selected.ingredients.map((s,i)=><span key={i}>{s}</span>)}</div><h3>{selected.fullRecipe?'Cooking instructions':'How it comes together'}</h3><ol>{selected.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p className="fine">{selected.fullRecipe?<>Recipe and photo from the imported food recipe collection. Categories are grouped automatically from recipe names. Cooking times and servings were not supplied.</>:<>A CookSmart summary of the recipe from <a href={selected.source} target="_blank" rel="noreferrer">{selected.publisher}</a>. Open the full recipe for exact quantities, detailed instructions, and cooking notes. Photo: {selected.publisher}.</>}</p></div></>}</dialog>
 </>;
}
